### ISSUE TITLE
`Updating ...` string not translated

### ISSUE THREAD

**Issue by Jobsecond** [Dreamtonics/svstudio-translations#16]
<img width="265" alt="Updating" src="https://user-images.githubusercontent.com/25559254/92297405-c4890880-eef3-11ea-973b-8e45c244c700.png">

I am using <code>zh-cn</code> language. However, when using the update feature, it still shows English <code>Updating ...</code>. I have checked the translation file, and it seems that there is a space between <code>Updating</code> and <code>...</code> in the software UI, but the translation txt file does not have spaces.

https://github.com/Dreamtonics/svstudio-translations/blob/98e9b8f9b94e36b4b0cf6a547a072f062c1881f1/zh-cn.txt#L247

**Comment by teha921** [comment]
Thanks for your feedback. There indeed is an extra space. We removed the space so its in line with the common style. Translation can stay the same. So until you get the update, it won't be translated. Sorry for the inconvenience.
