### ISSUE TITLE
Please merge the language updates

### ISSUE THREAD

**Issue by marsmaae** [Dreamtonics/svstudio-translations#86]
We're very thankful for your work, we know that the Dreamtonics' team is not big so they can't be in every not-so-necessary aspect like the extra languages. But I want to to ask that if consideration is taken for merge all the pull requests... there are languages that aren't updated since 1.5.0 update and the 1.7.0 are already there but not merged.

**Comment by crlotwhite** [comment]
Hello, I'm a Korean contributor.
For Korean, 1.6.0 and 1.7.0 PRs were written, but it has not been applied yet.
I am also looking forward to the translation results being applied. :)
